In [2]:
import pandas as pd
import numpy as np

# Loading the dataset

In [3]:
data_frame = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
data_frame

PassengerId  Survived  Pclass   
0              1         0       3  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp   
0                              Braund, Mr. Owen Harris    male  22.0      1  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## seeing the first 10 rows of the dataset

In [4]:
data_frame.head(10)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

# seeing all the data types of columns in the data frame

In [5]:
data_frame.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
data_frame.describe()

PassengerId    Survived      Pclass         Age       SibSp   
count   891.000000  891.000000  891.000000  714.000000  891.000000  \
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## Filter out those columns that have dtype as object

In [8]:
data_frame[['Name','Sex','Ticket','Cabin','Embarked']]

Name     Sex   
0                              Braund, Mr. Owen Harris    male  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [9]:
data_frame[['Name','Sex','Ticket','Cabin','Embarked']].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

## To get indexes of all the columns as datatype as object 

In [10]:
data_frame.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
data_frame.dtypes == 'object'
## This code is going to return true for all the columsn with datatype as object

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [12]:
a = data_frame.dtypes[data_frame.dtypes=='object'].index
a
## Here the a list contains all the index's of the type object.

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

## Here we are trying to describe these columns

In [13]:
data_frame[a].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

## automate such that the index must contain columns name with dtypes as int64

In [14]:
data_frame.dtypes == 'int64'

PassengerId     True
Survived        True
Pclass          True
Name           False
Sex            False
Age            False
SibSp           True
Parch           True
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [15]:
int_list = data_frame.dtypes[data_frame.dtypes=='int64'].index
int_list

Index(['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch'], dtype='object')

In [16]:
data_frame[int_list].describe()

PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

## pd.Categorical 

In [17]:
new_pclass = pd.Categorical(data_frame['Pclass'])
new_pclass

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

## Read the cabin data and read the first letter of it and make a new column

In [18]:
data_frame['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [19]:
## converting the object into string using .astype(str)
char_cabin = data_frame["Cabin"].astype(str)
char_cabin

0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
886     nan
887     B42
888     nan
889    C148
890     nan
Name: Cabin, Length: 891, dtype: object

In [20]:
## getting the first of each data row
new_cabin = [cabin[0] for cabin in char_cabin]
new_cabin

['n',
 'C',
 'n',
 'C',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'G',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'A',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'A',
 'D',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'E',
 'D',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'C',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'E'

In [21]:
new_cabin = pd.Categorical(new_cabin)
new_cabin

['n', 'C', 'n', 'C', 'n', ..., 'n', 'B', 'n', 'C', 'n']
Length: 891
Categories (9, object): ['A', 'B', 'C', 'D', ..., 'F', 'G', 'T', 'n']

# Now add that new_cabin into the dataset with the column name as cabin_1

In [22]:
data_frame['cabin_1'] = new_cabin
data_frame

PassengerId  Survived  Pclass   
0              1         0       3  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp   
0                              Braund, Mr. Owen Harris    male  22.0      1  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked cabin_1  
0        0         A/5 21171   7.2500   NaN        S       n  
1        0          PC 17599  71.2833   C85        C       C  
2        0  STON/O2. 3101282   7.9250   NaN        S       n  
3        0            113803  53.1000  C123        S       C  
4        0            373450   8.0500   NaN        S       n  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S       n  
887      0            112053  30.0000   B42        S       B  
888      2        W./C. 6607  23.4500   NaN        S       n  
889      0            111369  30.0000  C148        C       C  
890      0            370376   7.7500   NaN        Q       n  

[891 rows x 13 columns]

## Find all the indexes where there are null values

In [23]:
# first check describe and see where the null values are present
data_frame.describe()

PassengerId    Survived      Pclass         Age       SibSp   
count   891.000000  891.000000  891.000000  714.000000  891.000000  \
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [24]:
indexes = np.where(data_frame['Age'].isnull()==True)
len(indexes[0])
indexes

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888]),)

## extract the index where fare is the max

In [25]:
## this is used to find max fare
max(data_frame['Fare'])

512.3292

In [26]:
np.where(data_frame["Fare"]==max(data_frame["Fare"]))

(array([258, 679, 737]),)

In [27]:
data_frame.iloc[np.where(data_frame["Fare"]==max(data_frame["Fare"]))]

PassengerId  Survived  Pclass                                Name   
258          259         1       1                    Ward, Miss. Anna  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked   
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  \
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C   
737    male  35.0      0      0  PC 17755  512.3292         B101        C   

    cabin_1  
258       n  
679       B  
737       B

## Find the name and cabin of a persons whos has minimum age

In [28]:
min_age = min(data_frame['Age'])
min_age

0.42

In [29]:
age_index = np.where(data_frame['Age']==min_age)
age_index

(array([803]),)

In [30]:
data_frame.iloc[age_index][['Name','Cabin']]

Name Cabin
803  Thomas, Master. Assad Alexander   NaN

## Concatenation opereation to create a third column from 2 other columns

In [31]:
data_frame['Family'] = data_frame['SibSp'] + data_frame['Parch']
data_frame

PassengerId  Survived  Pclass   
0              1         0       3  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp   
0                              Braund, Mr. Owen Harris    male  22.0      1  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked cabin_1  Family  
0        0         A/5 21171   7.2500   NaN        S       n       1  
1        0          PC 17599  71.2833   C85        C       C       1  
2        0  STON/O2. 3101282   7.9250   NaN        S       n       0  
3        0            113803  53.1000  C123        S       C       1  
4        0            373450   8.0500   NaN        S       n       0  
..     ...               ...      ...   ...      ...     ...     ...  
886      0            211536  13.0000   NaN        S       n       0  
887      0            112053  30.0000   B42        S       B       0  
888      2        W./C. 6607  23.4500   NaN        S       n       3  
889      0            111369  30.0000  C148        C       C       0  
890      0            370376   7.7500   NaN        Q       n       0  

[891 rows x 14 columns]

In [32]:
max_family = max(data_frame['Family'])
max_family

10

In [33]:
family_index = np.where(data_frame['Family']==max_family)
family_index

(array([159, 180, 201, 324, 792, 846, 863]),)

In [34]:
data_frame.iloc[family_index]

PassengerId  Survived  Pclass                               Name     Sex   
159          160         0       3         Sage, Master. Thomas Henry    male  \
180          181         0       3       Sage, Miss. Constance Gladys  female   
201          202         0       3                Sage, Mr. Frederick    male   
324          325         0       3           Sage, Mr. George John Jr    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked cabin_1  Family  
159  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
180  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
201  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
324  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
792  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
846  NaN      8      2  CA. 2343  69.55   NaN        S       n      10  
863  NaN      8      2  CA. 2343  69.55   NaN        S       n      10

## Converting  list to series and dictinaries to series

In [35]:
labels = ['a','b','c']
mydata = [10,20,30]
d = {'a':10,'b':20,'c':30}

# converting a list to np array
arr = np.array(mydata)
arr

array([10, 20, 30])

In [36]:
pd.Series(mydata)
## in the below output we can see that the index's are 0,1,2 by defaults 

0    10
1    20
2    30
dtype: int64

In [37]:
pd.Series(mydata,index=labels)
## in this i am giving the index's to be the values of labels

a    10
b    20
c    30
dtype: int64

In [38]:
d = {'a':"abc",'b':20,'c':30}
## when you are trying to convert a dictionary to series then we need to pass the index values
pd.DataFrame(d,index=['m','n','o'])

a   b   c
m  abc  20  30
n  abc  20  30
o  abc  20  30

## Series Addition


### IN the below code we can see that series addition takes place element of 1st ser and it find the index of the same in the 2nd series and then add

In [39]:
ser1 = pd.Series([1,2,3,4],['CA','OR','CO','CA'])
ser2 = pd.Series([1,2,5,4],['CA','NV','AZ','OR'])
ser1 + ser2

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

# Conversion of 2D array into a DataFrame

In [40]:
from numpy.random import randn as rn
matrix_data = rn(5,4)
matrix_data

array([[-0.90776443,  1.13855569,  0.03843406,  0.08606824],
       [-0.28318794,  0.7619818 , -0.02216577,  1.54131463],
       [ 0.64085273, -0.74539865,  1.84791961,  0.39946286],
       [-1.27397823, -0.53623263, -0.5292423 , -0.1709423 ],
       [-1.00260316,  0.24323213, -0.28568199,  0.46337093]])

## This block of code is to make sure that whenever we want to generate random data but it has to be same it should not change then use the code below

In [74]:
from numpy.random import randn as rn
np.random.seed(1)
matrix_data_unchanged = rn(5,4)
matrix_data_unchanged

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435,  1.13376944, -1.09989127],
       [-0.17242821, -0.87785842,  0.04221375,  0.58281521]])

In [75]:
pd.DataFrame(matrix_data)
# Here you can see that the rows and columns are labeled by deafult.

0         1         2         3
0 -0.907764  1.138556  0.038434  0.086068
1 -0.283188  0.761982 -0.022166  1.541315
2  0.640853 -0.745399  1.847920  0.399463
3 -1.273978 -0.536233 -0.529242 -0.170942
4 -1.002603  0.243232 -0.285682  0.463371

In [76]:
row_labels = ['a','b','c','d','e']
col_labels = ['w','x','y','z']
df = pd.DataFrame(matrix_data,row_labels,col_labels)
# Now in the below output we can see that the row and the column names are given by us
df

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
b -0.283188  0.761982 -0.022166  1.541315
c  0.640853 -0.745399  1.847920  0.399463
d -1.273978 -0.536233 -0.529242 -0.170942
e -1.002603  0.243232 -0.285682  0.463371

# Data extraction from the matrix or any dataframe

In [44]:
## Extract data from a particular column
df['x']

a    1.138556
b    0.761982
c   -0.745399
d   -0.536233
e    0.243232
Name: x, dtype: float64

In [45]:
df['y']

a    0.038434
b   -0.022166
c    1.847920
d   -0.529242
e   -0.285682
Name: y, dtype: float64

In [46]:
df['w']

a   -0.907764
b   -0.283188
c    0.640853
d   -1.273978
e   -1.002603
Name: w, dtype: float64

In [47]:
df['z']

a    0.086068
b    1.541315
c    0.399463
d   -0.170942
e    0.463371
Name: z, dtype: float64

## to get the elements from a multiple column

In [48]:
df[['w','x']]

w         x
a -0.907764  1.138556
b -0.283188  0.761982
c  0.640853 -0.745399
d -1.273978 -0.536233
e -1.002603  0.243232

In [49]:
df

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
b -0.283188  0.761982 -0.022166  1.541315
c  0.640853 -0.745399  1.847920  0.399463
d -1.273978 -0.536233 -0.529242 -0.170942
e -1.002603  0.243232 -0.285682  0.463371

## Extract single row

In [50]:
df.loc['e']

w   -1.002603
x    0.243232
y   -0.285682
z    0.463371
Name: e, dtype: float64

In [51]:
df.iloc[4]
## the difference between iloc and loc is that loc can take the row values given by the user but iloc is able to take
## only the default values

w   -1.002603
x    0.243232
y   -0.285682
z    0.463371
Name: e, dtype: float64

## Get multiple rows of data

In [52]:
df.loc[['a','e']]

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
e -1.002603  0.243232 -0.285682  0.463371

In [53]:
df.iloc[[0,4]]

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
e -1.002603  0.243232 -0.285682  0.463371

## extract both row and column at once

In [54]:
df.iloc[[4,1,2],[1]]

x
e  0.243232
b  0.761982
c -0.745399

In [55]:
df

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
b -0.283188  0.761982 -0.022166  1.541315
c  0.640853 -0.745399  1.847920  0.399463
d -1.273978 -0.536233 -0.529242 -0.170942
e -1.002603  0.243232 -0.285682  0.463371

In [56]:
df.iloc[[1,2],[1,2]]

x         y
b  0.761982 -0.022166
c -0.745399  1.847920

In [57]:
df.iloc[[0,4],[0,3]]

w         z
a -0.907764  0.086068
e -1.002603  0.463371

In [58]:
df.loc['b':'d','w':'y']

w         x         y
b -0.283188  0.761982 -0.022166
c  0.640853 -0.745399  1.847920
d -1.273978 -0.536233 -0.529242

## Creating new columns

In [60]:
df['combine_sum_of_X_Y'] = df['x'] + df['y']
df

w         x         y         z   combine  combine_sum_of_X_Y
a -0.907764  1.138556  0.038434  0.086068  1.176990            1.176990
b -0.283188  0.761982 -0.022166  1.541315  0.739816            0.739816
c  0.640853 -0.745399  1.847920  0.399463  1.102521            1.102521
d -1.273978 -0.536233 -0.529242 -0.170942 -1.065475           -1.065475
e -1.002603  0.243232 -0.285682  0.463371 -0.042450           -0.042450

## Dropping the rows or columns

In [61]:
# df.drop('X') this is not going to drop the column X because it will get confused if that x is a row or a column
############# Hence use the beloew code to drop the column
df.drop('x',axis=1)

w         y         z   combine  combine_sum_of_X_Y
a -0.907764  0.038434  0.086068  1.176990            1.176990
b -0.283188 -0.022166  1.541315  0.739816            0.739816
c  0.640853  1.847920  0.399463  1.102521            1.102521
d -1.273978 -0.529242 -0.170942 -1.065475           -1.065475
e -1.002603 -0.285682  0.463371 -0.042450           -0.042450

In [63]:
df
## Here in the below output we can see that even after dropping x from the table it is still present in the dataframe

w         x         y         z   combine  combine_sum_of_X_Y
a -0.907764  1.138556  0.038434  0.086068  1.176990            1.176990
b -0.283188  0.761982 -0.022166  1.541315  0.739816            0.739816
c  0.640853 -0.745399  1.847920  0.399463  1.102521            1.102521
d -1.273978 -0.536233 -0.529242 -0.170942 -1.065475           -1.065475
e -1.002603  0.243232 -0.285682  0.463371 -0.042450           -0.042450

## Dropping the rows or columns permanently

In [64]:
df.drop('x',axis=1,inplace=True)

In [67]:
df
## Here we can see that x has been permanently removed from the dataframe because we have used inplace = True

w         y         z   combine  combine_sum_of_X_Y
a -0.907764  0.038434  0.086068  1.176990            1.176990
b -0.283188 -0.022166  1.541315  0.739816            0.739816
c  0.640853  1.847920  0.399463  1.102521            1.102521
d -1.273978 -0.529242 -0.170942 -1.065475           -1.065475
e -1.002603 -0.285682  0.463371 -0.042450           -0.042450

In [73]:
## Here i am dropping my row c using the code
# df.drop('c',inplace = True)
df

w         y         z   combine  combine_sum_of_X_Y
a -0.907764  0.038434  0.086068  1.176990            1.176990
b -0.283188 -0.022166  1.541315  0.739816            0.739816
d -1.273978 -0.529242 -0.170942 -1.065475           -1.065475
e -1.002603 -0.285682  0.463371 -0.042450           -0.042450

In [78]:
df
## Here i am recreating the dataframe again

w         x         y         z
a -0.907764  1.138556  0.038434  0.086068
b -0.283188  0.761982 -0.022166  1.541315
c  0.640853 -0.745399  1.847920  0.399463
d -1.273978 -0.536233 -0.529242 -0.170942
e -1.002603  0.243232 -0.285682  0.463371

## Here i am checking if the values of each cell is either true or false

In [81]:
print(df > 0)
## this will return true if the value is greater than 0 and false if the value is less than 0

       w      x      y      z
a  False   True   True   True
b  False   True  False   True
c   True  False   True   True
d  False  False  False  False
e  False   True  False   True


In [85]:
df.loc[['a','b','c'],['w','x','y']] > 0
## Here instead of getting the whole dataframe i am only considering the rows [a,b,c] and columns as [w,x,y]

w      x      y
a  False   True   True
b  False   True  False
c   True  False   True

In [86]:
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [ ]:
## Creating a Dataframe
df = pd.DataFrame(matrix_data,ind)