In [1]:
import numpy as np

In [4]:
a = np.array(['abcd',1,2])

In [5]:
type(a)

numpy.ndarray

## upcasting

In [6]:
b = np.array([1,2,3.0])

In [9]:
b
## here we can see that the array i gave was 1,2,3.0 but when i print the array it is doing upcasting and printing 1.,2.,3.

array([1., 2., 3.])

## two dimension array

In [12]:
mat = np.array([[1,2],
              [3,4]])

In [14]:
type(mat)

numpy.ndarray

## How to create a N dimension array

In [16]:
c = np.array([[1,2],[3,4]],ndmin=5)
c
## here we can see that the C array is a 5 dimension array

array([[[[[1, 2],
          [3, 4]]]]])

## how to change the datatype or convert 

In [24]:
d = np.array([[1,2,3]],dtype=complex)

In [26]:
d
## here in the below output i can see that even though i gave real values of data but given datatype as complex
## it has converted the data in the array to complex as in the form a + ij

array([[1.+0.j, 2.+0.j, 3.+0.j]])

## Data-type consisting of more than one element

In [ ]:
e = np.array([[1,2],[3,4]],dtype=[('a','i2'),('b','i8')])