In [1]:
import numpy as np

In [2]:
a = np.array(['abcd',1,2])

In [3]:
type(a)

numpy.ndarray

## upcasting

In [4]:
b = np.array([1,2,3.0])

In [5]:
b
## here we can see that the array i gave was 1,2,3.0 but when i print the array it is doing upcasting and printing 1.,2.,3.

array([1., 2., 3.])

## two dimension array

In [6]:
mat = np.array([[1,2],
              [3,4]])

In [7]:
type(mat)

numpy.ndarray

## How to create a N dimension array

In [8]:
c = np.array([[1,2],[3,4]],ndmin=5)
c
## here we can see that the C array is a 5 dimension array

array([[[[[1, 2],
          [3, 4]]]]])

## how to change the datatype or convert 

In [9]:
d = np.array([[1,2,3]],dtype=complex)

In [10]:
d
## here in the below output i can see that even though i gave real values of data but given datatype as complex
## it has converted the data in the array to complex as in the form a + ij

array([[1.+0.j, 2.+0.j, 3.+0.j]])

## Data-type consisting of more than one element

In [11]:
e = np.array([(1,2),(3,4)],dtype=[('a','i2'),('b','i8')])

In [12]:
e

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
type(e[0][0]) ## here we can see that i2 mean it is INT16

numpy.int16

In [14]:
type(e[0][1]) ## here we can see that i8 mean it is INT64

numpy.int64

## creating an array from subclasses

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
## the above is array
## now i converted the above array into a matrix
f = np.mat(np.array([[1,2],[3,4]]))

In [17]:
type(f)

numpy.matrix

## numpy.asarray

In [18]:
## convert a list into an array
a = [1,2]
type(a)

list

In [19]:
a = np.asarray(a)

In [20]:
type(a)

numpy.ndarray

In [21]:
a = np.array([1,2],dtype = np.float32)
a

array([1., 2.], dtype=float32)

In [22]:
np.asarray(np.array([1,2])) is a
## here we are getting false because the type of a is float32 and here np.array the dtype will be int64

False

In [23]:
np.asarray(a,dtype=np.float64) is a
## here we can see that asarray of type a is not float64 hence we can this is returning false

False

In [24]:
## Now we can see that it will return true becuase the dtype we are giving is float32
np.asarray(a,dtype = np.float32) is a

True

## subclasses or not

In [25]:
issubclass(np.matrix,np.ndarray)
## here we are saying is matrix the subclass of ndarray yes so it's returning true

True

In [26]:
issubclass(np.ndarray,np.matrix)
## here we are saying is ndarray the subclass of matrix no hence it's returning false

False

## numpy.asanyarray

In [27]:
## this will convert any non array fromat into a ndarray format
list1 = [1,2]
np.asanyarray(list1)

array([1, 2])

In [28]:
type(np.asanyarray(list1))

numpy.ndarray

In [29]:
## here we will see an example we know that matrixes are the subclasses of array i.e is array is super class of matrices
a = np.matrix([1,2])

In [30]:
a

matrix([[1, 2]])

In [31]:
np.array(a)

array([[1, 2]])

In [32]:
np.asarray(a)

array([[1, 2]])

In [33]:
np.asanyarray(a)

matrix([[1, 2]])

In [34]:
## i can see in the above 3 lines of code that np.array and np.asarray has converted the matrix into a array
## but np.asanarray has not converted the matrix into array.

## numpy copy

In [35]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [36]:
y = x ## here we are doing shallow copy

In [37]:
y

array([1, 2, 3])

In [38]:
y[0] = 100
y
## here we can see that change in values of y will effect the values in x, Hence this is called as shallow copy

array([100,   2,   3])

In [39]:
x

array([100,   2,   3])

In [40]:
z = np.copy(x) ## this is used to deep copy

In [41]:
z

array([100,   2,   3])

In [42]:
z[0] = 10
z
## here we can see that change in values of z will not effect the values in x, Hence this is called as deep copy

array([10,  2,  3])

In [43]:
x

array([100,   2,   3])

## numpy formfunction

In [44]:
## this is just a function that will be able to generate an random arrays
## SYNTAX:-
## np.fromfunction(function,size,**kwargs)

In [45]:
np.fromfunction(lambda i, j:i==j, (3,3),dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [46]:
np.fromfunction(lambda i, j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## numpy fromiter

In [48]:
## this is a function that we use to get an 1-D array from the iteratable object
##SYNTAX:-
## np.fromiter(iterable,datatype)

In [53]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x120100ba0>

In [54]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

## numpy fromstring

In [55]:
## this is function that we use to get an array from the string
##SYNTAX:-
## np.fromiter(string,seperator)
## The ultimate goal of this function is to get the string.

In [56]:
a = "234 234"

In [60]:
np.fromstring(a,sep=" ")
## here you can see that the above string a is converted into array of floats with seperator as space.

array([234., 234.])

In [63]:
np.fromstring('1, 2',float,sep=",")
## here we can see that we have given a string 1,2 and using np.fromstring we converted them into an array separating them by a comma

array([1., 2.])

## how to create a record from multiple flat arrays.

In [64]:
x1 = np.array([1,2,3,4])

In [65]:
x2 = np.array(['a','dd','xyz','12'])

In [67]:
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [68]:
np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

# Data types

In [69]:
arr = [1,2,3]
arr

[1, 2, 3]

In [70]:
np_arr = np.array(arr)
np_arr

array([1, 2, 3])

In [71]:
type(np_arr)

numpy.ndarray

In [72]:
my_mat = ([1,2,3],[4,5,6],[7,8,9])
my_mat

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [73]:
mat = np.array(my_mat)

In [74]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
type(mat)

numpy.ndarray

In [79]:
print("ndim of the array",mat.ndim) ## it will say how many dimensions the array or matrix is
print("the size of the array",mat.size) ## it will give the total number of elements present in the matrix
print("the shape of the array",mat.shape) ## it will give the shape of the array i.e (n*n)
print("the data types of the array",mat.dtype) ## it will return the datatype of the elements present in the array

ndim of the array 2
the size of the array 9
the shape of the array (3, 3)
the data types of the array int64


## tuples to ndarray

In [81]:
tup_arr = np.array([(1,2,3),(4,5,6)])
print(type(tup_arr))

<class 'numpy.ndarray'>


## arange and linespace

In [83]:
list(range(4,7))
## this will return the list that will contain the values from 4 till 6 since the last index is exclusive

[4, 5, 6]

In [85]:
list(range(1,11,2))
## this is going to return the values between 1 to 11 and will contain only alternate values
## since i used the step size to be 2

[1, 3, 5, 7, 9]

In [86]:
np.arange(5,16,2.3)

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [88]:
np.arange(16,0,-2)
## here we can see that the arange will give me a list of numbers in descending order since my step size is -2

array([16, 14, 12, 10,  8,  6,  4,  2])

In [91]:
np.linspace(1,5,50)
## here what's hapenning is that the linspace function si creating a record that contain 50 values and the number
## are in between 1 to 5

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

## matrix creation

In [92]:
np.zeros(5)
## it will create an array of size 5 with all zeros

array([0., 0., 0., 0., 0.])

In [95]:
np.zeros((3,4,2))
## this will contain 3 arrays of size (4,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [97]:
np.ones((5,2,8))
## this will contain 5 arrays of size (2,8)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [102]:
print(5 + np.ones((3,5)))
## this will create an array of ones of size (3,5) and then it will add 5 to each element like scalar addition

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


## numpy empty

In [105]:
## when there are empty arrays without any definiton then it will generate random values 
## since there is an array already existing hence it's giving 6

In [106]:
np.empty((3,5))
## here we are getting 6's because it the last array that is taking is 6.

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [107]:
## to create an identity matrixes
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## practise 1

In [108]:
## create a (3,4,8) array that contains all zeros

In [109]:
np.zeros((3,4,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [110]:
## generate data in an array between (4,8,80) and the number of points i need between 4 and 8 must be 80

In [111]:
np.linspace(4,8,num=80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [113]:
## take any list and convert the list into matrices
list1 = [1,2,3,4]
np.mat(list1)

matrix([[1, 2, 3, 4]])

In [118]:
## create an array of the shape (4,5,2) with all one's and print the dimesnsions, shape and data type of it
a = np.ones((4,5,2))

In [119]:
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [120]:
print("the dimensions of the array is :- ",a.ndim)
print("the shape of the array is :- ", a.shape)
print("the data type of the array is :- ",a.dtype)

the dimensions of the array is :-  3
the shape of the array is :-  (4, 5, 2)
the data type of the array is :-  float64


In [122]:
## create an array x1 of shape (3*3*3)
## create a array x2 of shape (3*3*3)
## perform x!+x2
x1 = np.ones((3,3,3))
x2 = np.zeros((3,3,3))
x1 + x2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## extract a diagonal or construct a diagonal array

In [123]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
## One of the most important thing to keep in mind is that when you are trying to resize the array then we need to make
## sure that the total elements in the orginal array must be in same in the reshape array as well
np.arange(16).reshape((8,2,1))

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [133]:
## here i am trying to give different dimensions compared to original
## i have 16 elements but i am going to give 20 elements just to see what happens
print(np.arange(16).reshape((20,2)))
## this is giving me none hence we cannot do that

ValueError: cannot reshape array of size 16 into shape (20,2)

In [134]:
print(np.arange(16).reshape(8,3))

ValueError: cannot reshape array of size 16 into shape (8,3)

## using -1 just to make sure we can understand how that works

In [136]:
np.arange(16).reshape(-1,4)
## here we can see that when i say (-1,4) then it can understand that there should be 4 instead of -1 since 
## 4 * 4 is 16.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
np.arange(20).reshape(4,-1)
## here we can see that we are getting (4,5) array but we gave (4,-1) the computer understands that -1 should be 5
## only then elements of the array are 20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [140]:
## in the above 2 codes boxes we can see that -1 is used but we can use any negative number and the system
##. can understand.
np.arange(20).reshape(5,-4567)
## see here we used -4567 but the computer understood.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## get the diagonal elements

In [144]:
x = np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
## here i have an array x get the diagonal elements only
np.diag(x,k=0)
## here i can see that we can get the diagonal elements

array([ 0,  5, 10, 15])

In [150]:
## lets try some code with different values of k and understand how the diagonal elements and what are we getting
np.diag(x,k= -1) ## i should be getting 4,9,14 as the output

array([ 4,  9, 14])

In [151]:
np.diag(x,k = 1) ## now i should be getting 1,6,11

array([ 1,  6, 11])