In [1]:
import numpy as np

In [2]:
a = np.array(['abcd',1,2])

In [3]:
type(a)

numpy.ndarray

## upcasting

In [4]:
b = np.array([1,2,3.0])

In [5]:
b
## here we can see that the array i gave was 1,2,3.0 but when i print the array it is doing upcasting and printing 1.,2.,3.

array([1., 2., 3.])

## two dimension array

In [6]:
mat = np.array([[1,2],
              [3,4]])

In [7]:
type(mat)

numpy.ndarray

## How to create a N dimension array

In [8]:
c = np.array([[1,2],[3,4]],ndmin=5)
c
## here we can see that the C array is a 5 dimension array

array([[[[[1, 2],
          [3, 4]]]]])

## how to change the datatype or convert 

In [9]:
d = np.array([[1,2,3]],dtype=complex)

In [10]:
d
## here in the below output i can see that even though i gave real values of data but given datatype as complex
## it has converted the data in the array to complex as in the form a + ij

array([[1.+0.j, 2.+0.j, 3.+0.j]])

## Data-type consisting of more than one element

In [11]:
e = np.array([(1,2),(3,4)],dtype=[('a','i2'),('b','i8')])

In [12]:
e

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
type(e[0][0]) ## here we can see that i2 mean it is INT16

numpy.int16

In [14]:
type(e[0][1]) ## here we can see that i8 mean it is INT64

numpy.int64

## creating an array from subclasses

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
## the above is array
## now i converted the above array into a matrix
f = np.mat(np.array([[1,2],[3,4]]))

In [17]:
type(f)

numpy.matrix

## numpy.asarray

In [18]:
## convert a list into an array
a = [1,2]
type(a)

list

In [19]:
a = np.asarray(a)

In [20]:
type(a)

numpy.ndarray

In [21]:
a = np.array([1,2],dtype = np.float32)
a

array([1., 2.], dtype=float32)

In [22]:
np.asarray(np.array([1,2])) is a
## here we are getting false because the type of a is float32 and here np.array the dtype will be int64

False

In [23]:
np.asarray(a,dtype=np.float64) is a
## here we can see that asarray of type a is not float64 hence we can this is returning false

False

In [24]:
## Now we can see that it will return true becuase the dtype we are giving is float32
np.asarray(a,dtype = np.float32) is a

True

## subclasses or not

In [25]:
issubclass(np.matrix,np.ndarray)
## here we are saying is matrix the subclass of ndarray yes so it's returning true

True

In [26]:
issubclass(np.ndarray,np.matrix)
## here we are saying is ndarray the subclass of matrix no hence it's returning false

False

## numpy.asanyarray

In [27]:
## this will convert any non array fromat into a ndarray format
list1 = [1,2]
np.asanyarray(list1)

array([1, 2])

In [28]:
type(np.asanyarray(list1))

numpy.ndarray

In [29]:
## here we will see an example we know that matrixes are the subclasses of array i.e is array is super class of matrices
a = np.matrix([1,2])

In [30]:
a

matrix([[1, 2]])

In [31]:
np.array(a)

array([[1, 2]])

In [32]:
np.asarray(a)

array([[1, 2]])

In [33]:
np.asanyarray(a)

matrix([[1, 2]])

In [34]:
## i can see in the above 3 lines of code that np.array and np.asarray has converted the matrix into a array
## but np.asanarray has not converted the matrix into array.

## numpy copy

In [35]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [36]:
y = x ## here we are doing shallow copy

In [37]:
y

array([1, 2, 3])

In [38]:
y[0] = 100
y
## here we can see that change in values of y will effect the values in x, Hence this is called as shallow copy

array([100,   2,   3])

In [39]:
x

array([100,   2,   3])

In [40]:
z = np.copy(x) ## this is used to deep copy

In [41]:
z

array([100,   2,   3])

In [42]:
z[0] = 10
z
## here we can see that change in values of z will not effect the values in x, Hence this is called as deep copy

array([10,  2,  3])

In [43]:
x

array([100,   2,   3])

## numpy formfunction

In [44]:
## this is just a function that will be able to generate an random arrays
## SYNTAX:-
## np.fromfunction(function,size,**kwargs)

In [45]:
np.fromfunction(lambda i, j:i==j, (3,3),dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [46]:
np.fromfunction(lambda i, j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## numpy fromiter

In [47]:
## this is a function that we use to get an 1-D array from the iteratable object
##SYNTAX:-
## np.fromiter(iterable,datatype)

In [48]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x108fad310>

In [49]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

## numpy fromstring

In [50]:
## this is function that we use to get an array from the string
##SYNTAX:-
## np.fromiter(string,seperator)
## The ultimate goal of this function is to get the string.

In [51]:
a = "234 234"

In [52]:
np.fromstring(a,sep=" ")
## here you can see that the above string a is converted into array of floats with seperator as space.

array([234., 234.])

In [53]:
np.fromstring('1, 2',float,sep=",")
## here we can see that we have given a string 1,2 and using np.fromstring we converted them into an array separating them by a comma

array([1., 2.])

## how to create a record from multiple flat arrays.

In [54]:
x1 = np.array([1,2,3,4])

In [55]:
x2 = np.array(['a','dd','xyz','12'])

In [56]:
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [57]:
np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

# Data types

In [58]:
arr = [1,2,3]
arr

[1, 2, 3]

In [59]:
np_arr = np.array(arr)
np_arr

array([1, 2, 3])

In [60]:
type(np_arr)

numpy.ndarray

In [61]:
my_mat = ([1,2,3],[4,5,6],[7,8,9])
my_mat

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [62]:
mat = np.array(my_mat)

In [63]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
type(mat)

numpy.ndarray

In [65]:
print("ndim of the array",mat.ndim) ## it will say how many dimensions the array or matrix is
print("the size of the array",mat.size) ## it will give the total number of elements present in the matrix
print("the shape of the array",mat.shape) ## it will give the shape of the array i.e (n*n)
print("the data types of the array",mat.dtype) ## it will return the datatype of the elements present in the array

ndim of the array 2
the size of the array 9
the shape of the array (3, 3)
the data types of the array int64


## tuples to ndarray

In [66]:
tup_arr = np.array([(1,2,3),(4,5,6)])
print(type(tup_arr))

<class 'numpy.ndarray'>


## arange and linespace

In [67]:
list(range(4,7))
## this will return the list that will contain the values from 4 till 6 since the last index is exclusive

[4, 5, 6]

In [68]:
list(range(1,11,2))
## this is going to return the values between 1 to 11 and will contain only alternate values
## since i used the step size to be 2

[1, 3, 5, 7, 9]

In [69]:
np.arange(5,16,2.3)

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [70]:
np.arange(16,0,-2)
## here we can see that the arange will give me a list of numbers in descending order since my step size is -2

array([16, 14, 12, 10,  8,  6,  4,  2])

In [71]:
np.linspace(1,5,50)
## here what's hapenning is that the linspace function si creating a record that contain 50 values and the number
## are in between 1 to 5

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

## matrix creation

In [72]:
np.zeros(5)
## it will create an array of size 5 with all zeros

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros((3,4,2))
## this will contain 3 arrays of size (4,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [75]:
np.ones((5,2,8))
## this will contain 5 arrays of size (2,8)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [76]:
print(5 + np.ones((3,5)))
## this will create an array of ones of size (3,5) and then it will add 5 to each element like scalar addition

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


## numpy empty

In [77]:
## when there are empty arrays without any definiton then it will generate random values 
## since there is an array already existing hence it's giving 6

In [78]:
np.empty((3,5))
## here we are getting 6's because it the last array that is taking is 6.

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [79]:
## to create an identity matrixes
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## practise 1

In [80]:
## create a (3,4,8) array that contains all zeros

In [81]:
np.zeros((3,4,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [82]:
## generate data in an array between (4,8,80) and the number of points i need between 4 and 8 must be 80

In [83]:
np.linspace(4,8,num=80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [84]:
## take any list and convert the list into matrices
list1 = [1,2,3,4]
np.mat(list1)

matrix([[1, 2, 3, 4]])

In [85]:
## create an array of the shape (4,5,2) with all one's and print the dimesnsions, shape and data type of it
a = np.ones((4,5,2))

In [86]:
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [87]:
print("the dimensions of the array is :- ",a.ndim)
print("the shape of the array is :- ", a.shape)
print("the data type of the array is :- ",a.dtype)

the dimensions of the array is :-  3
the shape of the array is :-  (4, 5, 2)
the data type of the array is :-  float64


In [88]:
## create an array x1 of shape (3*3*3)
## create a array x2 of shape (3*3*3)
## perform x!+x2
x1 = np.ones((3,3,3))
x2 = np.zeros((3,3,3))
x1 + x2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## extract a diagonal or construct a diagonal array

In [89]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
## One of the most important thing to keep in mind is that when you are trying to resize the array then we need to make
## sure that the total elements in the orginal array must be in same in the reshape array as well
np.arange(16).reshape((8,2,1))

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [91]:
## here i am trying to give different dimensions compared to original
## i have 16 elements but i am going to give 20 elements just to see what happens
#print(np.arange(16).reshape((20,2)))
## this is giving me none hence we cannot do that

In [92]:
#print(np.arange(16).reshape(8,3))

## using -1 just to make sure we can understand how that works

In [93]:
np.arange(16).reshape(-1,4)
## here we can see that when i say (-1,4) then it can understand that there should be 4 instead of -1 since 
## 4 * 4 is 16.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
np.arange(20).reshape(4,-1)
## here we can see that we are getting (4,5) array but we gave (4,-1) the computer understands that -1 should be 5
## only then elements of the array are 20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
## in the above 2 codes boxes we can see that -1 is used but we can use any negative number and the system
##. can understand.
np.arange(20).reshape(5,-4567)
## see here we used -4567 but the computer understood.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## get the diagonal elements

In [96]:
x = np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
## here i have an array x get the diagonal elements only
np.diag(x,k=0)
## here i can see that we can get the diagonal elements

array([ 0,  5, 10, 15])

In [98]:
## lets try some code with different values of k and understand how the diagonal elements and what are we getting
np.diag(x,k= -1) ## i should be getting 4,9,14 as the output

array([ 4,  9, 14])

In [99]:
np.diag(x,k = 1) ## now i should be getting 1,6,11

array([ 1,  6, 11])

In [100]:
np.diag(np.diag(x,k=0))
## we can see below that it reconstructed the whole matrix and it only has the diagonal elements from the original array

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## diagflat

In [101]:
## it will flatten any array and will create a new array and construct a matrix with it.
np.diagflat([[1,2],[3,4]])
## see here is the value of k = 0 hence the flatten elements are kept in the principal diagonal elements

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [102]:
np.diagflat([1,2],1)
## here we want to flatten the[1,2] first then it will construct an array and then it will keep the diagonal at k = 1

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

## numpy tri

In [103]:
## it is an array with ones at and below that diagonal

In [104]:
np.tri(3,5,k=0,dtype=int)
## the values of the k determines what diagonal elements are filled and under that.

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [105]:
np.tri(N=4,k=0,dtype=int)
## here we can see that we have given only the value of N and not M hence what happens is that internally the value
## of M is going to be equal to N

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

# numpy tril

In [106]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])
## this will return the lower triangle of the matrix

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [107]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],k=-2) ## here the output has to be 7

array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

# numpy triu

In [108]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
## this will return the upper triangle of the matrix

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [109]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],k=1) ## here the output must 2 6 and 3

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

## Random Number generation

In [110]:
print(np.random.rand(2,3))
## here i am going to print a matrix with dimensions with 2 rows and 3 columns and the data that is generated using 
## the rand is uniformly distributed

[[0.50886385 0.03145452 0.30796071]
 [0.01159301 0.3720287  0.05567618]]


In [111]:
print(np.random.randn(4,3))
## this is going to print a matrix with dimension with 4 rows and 3 columns and the data that is generated using
## randn is normally distributed

[[ 0.79028051  0.14714341 -0.49561723]
 [ 1.1797012   1.18822855  1.10734472]
 [ 0.14215087 -1.84815367  2.54844137]
 [ 0.02962609  0.11899055 -0.04780335]]


In [112]:
print(np.random.randint(1,10))

7


In [113]:
print("The random matrix that is generated by using the random function with values between 1 - 100")
print(np.random.randint(1,100,(4,4)))

The random matrix that is generated by using the random function with values between 1 - 100
[[13 19 75 26]
 [97 71 49 10]
 [56 98 27 14]
 [34 93 80 84]]


## Reshaping

In [114]:
from numpy.random import randint as ri
a = ri(1,100,30) ## this will genereate a list of 30 numbers in between 1-100
a

array([34, 65, 34, 34, 35, 96, 21, 50, 56, 37, 76, 12, 99, 57, 88, 79, 84,
        1, 38, 66, 22, 39, 80, 73, 87, 84, 64,  5, 38, 10])

In [115]:
b = a.reshape(2,3,5)
b

array([[[34, 65, 34, 34, 35],
        [96, 21, 50, 56, 37],
        [76, 12, 99, 57, 88]],

       [[79, 84,  1, 38, 66],
        [22, 39, 80, 73, 87],
        [84, 64,  5, 38, 10]]])

In [116]:
c = a.reshape(6,-19292)
c
## this will give a 6*5 dimension matrix even though we gave a -19292 as a dimension the computer will understand 
## because the shape is 1*30 there are 30 elements it will divide the 30 by 6 and then left is 5 hence (6,5)

array([[34, 65, 34, 34, 35],
       [96, 21, 50, 56, 37],
       [76, 12, 99, 57, 88],
       [79, 84,  1, 38, 66],
       [22, 39, 80, 73, 87],
       [84, 64,  5, 38, 10]])

In [117]:
A = ri(1,100,10)

In [118]:
## doing np.sort operation
print("Before Sorting")
print(A)
print("After sorting")
print(np.sort(A))

Before Sorting
[80  3  3  1 43 13 46  3 69 65]
After sorting
[ 1  3  3  3 13 43 46 65 69 80]


In [119]:
M = ri(1,100,25).reshape(5,5)
M

array([[92, 88, 66, 57, 77],
       [68, 44, 89,  7, 44],
       [16, 18, 84, 22, 92],
       [68, 99, 34, 27, 14],
       [42, 54, 45, 45,  4]])

In [120]:
print(np.sort(M,axis=1,kind='mergesort'))
## here iam trying to perform the sort operation on columns using merge sort

[[57 66 77 88 92]
 [ 7 44 44 68 89]
 [16 18 22 84 92]
 [14 27 34 68 99]
 [ 4 42 45 45 54]]


In [121]:
## here in the above matrix we can see that the matrix looks sorted but itseems likes it got sorted with rows but
## specified it use the columns
## Many poeple get confused here this is happening becuase when we say sort axis=1 then it will take each row(data)
## and sort it column wise

## ARGMAX

In [122]:
M

array([[92, 88, 66, 57, 77],
       [68, 44, 89,  7, 44],
       [16, 18, 84, 22, 92],
       [68, 99, 34, 27, 14],
       [42, 54, 45, 45,  4]])

In [123]:
M.argmax(axis=1)

array([0, 2, 4, 1, 1])

In [124]:
M.argmax(axis=0)

array([0, 3, 1, 0, 2])

In [125]:
c.argmax()

12

## indexing and slicing

In [126]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
print("The element at index 7 is ",arr[7])

The element at index 7 is  7


In [128]:
print("3rd and 5th index using step ",arr[3:6:2])

3rd and 5th index using step  [3 5]


In [129]:
print("printing the number's in reverse order ",arr[-1:8:-1])

printing the number's in reverse order  [10  9]


In [130]:
import numpy as np

In [139]:
mat = np.array(ri(10,100,45)).reshape(3,5,3)
mat

array([[[99, 85, 16],
        [34, 77, 57],
        [72, 13, 92],
        [64, 38, 81],
        [79, 69, 12]],

       [[70, 81, 83],
        [39, 74, 56],
        [32, 71, 18],
        [26, 21, 91],
        [21, 31, 74]],

       [[17, 31, 92],
        [56, 61, 58],
        [44, 65, 91],
        [35, 88, 26],
        [32, 50, 24]]])

In [132]:
mat[1][1]

array([78, 32, 57])

In [133]:
mat[1:4,3:5]
## this will give me the 2nd and 3rd matrix and it will give me the 3rd index and 4th index row of the matrix

array([[[62, 42, 76],
        [15, 52, 29]],

       [[10, 49, 62],
        [43, 77, 92]]])

In [134]:
mat[0:3,[1,3]] 
## i think this should 1st and 3rd column of all the matrices from the above matrix

array([[[33, 29, 99],
        [99, 33, 93]],

       [[78, 32, 57],
        [62, 42, 76]],

       [[95, 47, 20],
        [10, 49, 62]]])

In [135]:
mat[0][:,1]
## slicing operation [rows,columns]

array([96, 29, 22, 33, 21])

In [136]:
mat

array([[[37, 96, 37],
        [33, 29, 99],
        [63, 22, 99],
        [99, 33, 93],
        [50, 21, 74]],

       [[41, 27, 17],
        [78, 32, 57],
        [80, 24, 59],
        [62, 42, 76],
        [15, 52, 29]],

       [[44, 84, 78],
        [95, 47, 20],
        [67, 93, 68],
        [10, 49, 62],
        [43, 77, 92]]])

In [137]:
mat[0:3,[0,1]]

array([[[37, 96, 37],
        [33, 29, 99]],

       [[41, 27, 17],
        [78, 32, 57]],

       [[44, 84, 78],
        [95, 47, 20]]])

## SubSetting

In [142]:
mat1 = np.array(ri(20,100,15)).reshape(3,-100)
mat1

array([[68, 37, 61, 55, 87],
       [71, 47, 98, 54, 24],
       [48, 39, 48, 24, 35]])

## trying to see what elements are greater than 50

In [143]:
mat1>50

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False]])

## trying to print only those elements that are greater than 50

In [144]:
mat1[mat1>50]

array([68, 61, 55, 87, 71, 98, 54])

## Universal Functions

In [146]:
mat_1 = np.array(ri(1,10,9)).reshape(3,3)
mat_2 = np.array(ri(1,10,9)).reshape(3,3)
mat_1

array([[3, 8, 5],
       [5, 2, 7],
       [3, 4, 9]])

In [147]:
mat_2

array([[1, 2, 3],
       [3, 4, 8],
       [2, 1, 5]])

In [149]:
mat_1*mat_2
## this will just multiply the elements with same indexes

array([[ 3, 16, 15],
       [15,  8, 56],
       [ 6,  4, 45]])

In [151]:
mat_1@mat_2
## here we are performing matrix multiplication

array([[37, 43, 98],
       [25, 25, 66],
       [33, 31, 86]])

In [153]:
## performing and checking what happens when we divide by zero
## case 1:- just a random number
print(5/0)

ZeroDivisionError: division by zero

In [154]:
## case 2:- An element of an numpy array
mat_1/0

/var/folders/b0/y0q5l7lx61g3k6f4zvy9__4h0000gn/T/ipykernel_22193/2773347517.py:2: RuntimeWarning: divide by zero encountered in divide
  mat_1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [156]:
## addition of scalar
## that number is added to the each element of the array

In [157]:
100 + mat_1

array([[103, 108, 105],
       [105, 102, 107],
       [103, 104, 109]])

In [158]:
## power operation
## case 1:- using the double start(**)
mat_1**3

array([[ 27, 512, 125],
       [125,   8, 343],
       [ 27,  64, 729]])

In [159]:
## case 2:- using the pow function
pow(mat_1,3)

array([[ 27, 512, 125],
       [125,   8, 343],
       [ 27,  64, 729]])

## BroadCasting

In [161]:
mat_bc = np.zeros((4,4))
mat_bc

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [163]:
mat_bc + 100
## this is called as element wise broadcasting operation because we are performing this element wise.

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [164]:
add_rows = np.array([1,0,2,5])
add_rows

array([1, 0, 2, 5])

In [166]:
add_rows + mat_bc
## here we can see that the add_rows has been braodcasted for each and every element of the array.

array([[1., 0., 2., 5.],
       [1., 0., 2., 5.],
       [1., 0., 2., 5.],
       [1., 0., 2., 5.]])