In [1]:
import numpy as np

In [2]:
a = np.array(['abcd',1,2])

In [3]:
type(a)

numpy.ndarray

## upcasting

In [4]:
b = np.array([1,2,3.0])

In [5]:
b
## here we can see that the array i gave was 1,2,3.0 but when i print the array it is doing upcasting and printing 1.,2.,3.

array([1., 2., 3.])

## two dimension array

In [6]:
mat = np.array([[1,2],
              [3,4]])

In [7]:
type(mat)

numpy.ndarray

## How to create a N dimension array

In [8]:
c = np.array([[1,2],[3,4]],ndmin=5)
c
## here we can see that the C array is a 5 dimension array

array([[[[[1, 2],
          [3, 4]]]]])

## how to change the datatype or convert 

In [9]:
d = np.array([[1,2,3]],dtype=complex)

In [10]:
d
## here in the below output i can see that even though i gave real values of data but given datatype as complex
## it has converted the data in the array to complex as in the form a + ij

array([[1.+0.j, 2.+0.j, 3.+0.j]])

## Data-type consisting of more than one element

In [11]:
e = np.array([(1,2),(3,4)],dtype=[('a','i2'),('b','i8')])

In [12]:
e

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
type(e[0][0]) ## here we can see that i2 mean it is INT16

numpy.int16

In [14]:
type(e[0][1]) ## here we can see that i8 mean it is INT64

numpy.int64

## creating an array from subclasses

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
## the above is array
## now i converted the above array into a matrix
f = np.mat(np.array([[1,2],[3,4]]))

In [17]:
type(f)

numpy.matrix

## numpy.asarray

In [18]:
## convert a list into an array
a = [1,2]
type(a)

list

In [19]:
a = np.asarray(a)

In [20]:
type(a)

numpy.ndarray

In [21]:
a = np.array([1,2],dtype = np.float32)
a

array([1., 2.], dtype=float32)

In [22]:
np.asarray(np.array([1,2])) is a
## here we are getting false because the type of a is float32 and here np.array the dtype will be int64

False

In [23]:
np.asarray(a,dtype=np.float64) is a
## here we can see that asarray of type a is not float64 hence we can this is returning false

False

In [24]:
## Now we can see that it will return true becuase the dtype we are giving is float32
np.asarray(a,dtype = np.float32) is a

True

## subclasses or not

In [25]:
issubclass(np.matrix,np.ndarray)
## here we are saying is matrix the subclass of ndarray yes so it's returning true

True

In [26]:
issubclass(np.ndarray,np.matrix)
## here we are saying is ndarray the subclass of matrix no hence it's returning false

False

## numpy.asanyarray

In [27]:
## this will convert any non array fromat into a ndarray format
list1 = [1,2]
np.asanyarray(list1)

array([1, 2])

In [28]:
type(np.asanyarray(list1))

numpy.ndarray

In [29]:
## here we will see an example we know that matrixes are the subclasses of array i.e is array is super class of matrices
a = np.matrix([1,2])

In [30]:
a

matrix([[1, 2]])

In [31]:
np.array(a)

array([[1, 2]])

In [32]:
np.asarray(a)

array([[1, 2]])

In [33]:
np.asanyarray(a)

matrix([[1, 2]])

In [34]:
## i can see in the above 3 lines of code that np.array and np.asarray has converted the matrix into a array
## but np.asanarray has not converted the matrix into array.