In [1]:
import numpy as np

In [4]:
a = np.array(['abcd',1,2])

In [5]:
type(a)

numpy.ndarray

## upcasting

In [6]:
b = np.array([1,2,3.0])

In [9]:
b
## here we can see that the array i gave was 1,2,3.0 but when i print the array it is doing upcasting and printing 1.,2.,3.

array([1., 2., 3.])

## two dimension array

In [12]:
mat = np.array([[1,2],
              [3,4]])

In [14]:
type(mat)

numpy.ndarray

## How to create a N dimension array

In [16]:
c = np.array([[1,2],[3,4]],ndmin=5)
c
## here we can see that the C array is a 5 dimension array

array([[[[[1, 2],
          [3, 4]]]]])

## how to change the datatype or convert 

In [24]:
d = np.array([[1,2,3]],dtype=complex)

In [26]:
d
## here in the below output i can see that even though i gave real values of data but given datatype as complex
## it has converted the data in the array to complex as in the form a + ij

array([[1.+0.j, 2.+0.j, 3.+0.j]])

## Data-type consisting of more than one element

In [29]:
e = np.array([(1,2),(3,4)],dtype=[('a','i2'),('b','i8')])

In [30]:
e

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [33]:
type(e[0][0]) ## here we can see that i2 mean it is INT16

numpy.int16

In [34]:
type(e[0][1]) ## here we can see that i8 mean it is INT64

numpy.int64

## creating an array from subclasses

In [35]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [37]:
## the above is array
## now i converted the above array into a matrix
f = np.mat(np.array([[1,2],[3,4]]))

In [38]:
type(f)

numpy.matrix

## numpy.asarray

In [42]:
## convert a list into an array
a = [1,2]
type(a)

list

In [43]:
a = np.asarray(a)

In [45]:
type(a)

numpy.ndarray

In [48]:
a = np.array([1,2],dtype = np.float32)
a

array([1., 2.], dtype=float32)

In [50]:
np.asarray(np.array([1,2])) is a
## here we are getting false because the type of a is float32 and here 

False